### ISSUE TITLE
disableReturn makes statement disappear

### ISSUE THREAD

**Issue by diana1357** [AskiaADX/StatementList#3] opened 2017-10-04 09:19 UTC
When disable return is set to "1" the statement disappers. 

![disable1](https://user-images.githubusercontent.com/20987595/31168405-1d601340-a8ed-11e7-8434-9866b807e5a4.png)
![disable2](https://user-images.githubusercontent.com/20987595/31168431-33d281c6-a8ed-11e7-9e15-08e693311795.png)

**Comment by Djedj** [comment] 2017-10-04 09:57
Hi Diana,

Can you tell us more about how to reproduce cause i just tested it and it seems to works fine.
I tested this in ADXStudio and also in Design 5.4.6 using the qex located in example folder of the repo.

Thks in advance

**Comment by diana1357** [comment] 2017-10-04 11:26
Hi

In that case it could be the version of Askia Design, as I'm using 5.4.4.1? 

In Studio if I change the value from 0 and 1 the question looks like in the images above. I've also attached a qex I'm working with. 
[StatementList_Test.zip](https://github.com/AskiaADX/StatementList/files/1355579/StatementList_Test.zip)

**Comment by Djedj** [comment] 2017-10-04 13:02
Hi Diana,

The problem is about the option Hide Next Button. I know how to fix it so will do a new version of the adc

Best Regards

**Comment by Djedj** [comment] 2017-10-04 13:22
Hi Diana,

It should be fixed on the latest version of the adc v2.0.4 and available in the repo

Let us know if it's ok now ?

Best Regards

**Closed** 2017-10-04 15:15 UTC

**Comment by diana1357** [comment] 2017-10-05 13:27
Thank you, have tested and it works! :+1:
